# Practice 2 - Numpy
Students are required to complete the code implementation for Problems 1-7, and to conduct exploratory analysis for Problems 8 and 9, providing well-reasoned answers to the corresponding questions.

                                                                                                      
### DDL: Oct.12
* The practice will be checked in this lab class or the next lab class before the DDL by teachers or SAs.

#### What will be tested: 
* That you understand every line of your code, not just copy from somewhere 
* That your program compiles correctly
* Correctness of the program logic 
* That the result is obtained in a reasonable time 

#### Grading: 
* Submissions on time: 60-100 points.
* Late submissions  : 0 points. 

**Q1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.**

In [ ]:
import numpy as np

a = np.ones((10,10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Q2. Create a 5*5 matrix with each row being 0 to 4.**

In [2]:
a = np.arange(5)
np.vstack((a,a,a,a,a))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

**Q3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]]).**

In [11]:
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

**Q4. output all the odd numbers in the array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].**
     
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [4]:
a = np.arange(10)
b = a[a%2==1]
b


array([1, 3, 5, 7, 9])

**Q5. Apply Z-score normalization to a 5×5 random matrix.**

In [5]:
a = np.random.rand(5,5)
print(a)

mean = np.mean(a)
std = np.std(a)
g = (a - mean) / std
g


[[0.65616646 0.7829468  0.7397682  0.53842771 0.1185692 ]
 [0.87281173 0.71574819 0.98616301 0.1310225  0.35968703]
 [0.5462151  0.69715634 0.58385483 0.71629695 0.23705518]
 [0.04531454 0.63616981 0.81030055 0.06948089 0.1966204 ]
 [0.98776863 0.25565077 0.4269821  0.47076292 0.81015632]]


array([[ 0.42422961,  0.87048589,  0.71850082,  0.00979897, -1.46806819],
       [ 1.18680301,  0.63395235,  1.58579012, -1.42423361, -0.61935342],
       [ 0.03720994,  0.5685106 ,  0.16969866,  0.63588394, -1.05100734],
       [-1.7259185 ,  0.35384305,  0.96676883, -1.64085497, -1.19333442],
       [ 1.59144177, -0.98555241, -0.38248034, -0.22837549,  0.96626115]])

**Q6.Generate a random 10×2 matrix representing Cartesian coordinates, and transform the coordinates into their polar form.**

In [8]:
a = np.random.rand(10,2)
print(f"X,Y:{a[:,0]}{a[:,1]}")
r = np.sqrt(a[:,0]**2 + a[:,1]**2)
theta = np.arccos(a[:,0] / r)
print(f"R:{r}\n Theta:{theta}")

X,Y:[0.47069568 0.05474497 0.2305052  0.77870799 0.57246276 0.33593872
 0.63624929 0.70666013 0.441537   0.25425968][0.99809633 0.24244615 0.62083545 0.52912236 0.37519675 0.48022738
 0.81354933 0.49442997 0.66987906 0.04877251]
R:[1.10351743 0.24855009 0.66224565 0.94146514 0.68446052 0.58606584
 1.03279991 0.86245553 0.80230473 0.25889524]
 Theta:[1.13013111 1.3487181  1.21528901 0.59682614 0.58016768 0.96037851
 0.9070868  0.61050548 0.98802998 0.18951952]


**Q7.Given the vector [1, 2, 3, 4, 5], construct a new vector by inserting three consecutive zeros between each element.**

In [10]:
a = np.arange(1,6)
b = np.zeros(len(a) + (len(a)-1)*3)
b[::4] = a
b

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

**Q8. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))


In [13]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


**Q9. What are the result of the following expressions?First guess a result, then print the result, and finally find why.**
(Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)




In [15]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\33649\AppData\Local\Temp\ipykernel_11572\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\33649\AppData\Local\Temp\ipykernel_11572\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\33649\AppData\Local\Temp\ipykernel_11572\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))
